name: MiniGames-Core
main: MGC\MGC
version: 1.0
api: [2.0.0]
authors: [VCraftMCPE.RagingShadow123]
description: a Simple MiniGames servers System.
commands:
 MGC:
  description: "See commands list"
  usage: "/MGC <page> "
  permission: MGC.command
